# Generated by Django 4.1.7 on 2024-03-11 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaefin',
            name='datafinal',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 33, 19, 326537)),
        ),
        migrations.AlterField(
            model_name='movimentodetalhado',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 33, 19, 329536)),
        ),
    ]
